name: Python Deliberate Practice V2 - Master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.1]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: dschep/install-pipenv-action@v1
        with:
          version: 2021.5.29
      
      - uses: dschep/install-pipenv-action@v1
      
      - name: Pipenv install and test
        run: |
          pipenv install
          pipenv run test