name: "Python Deliberate Practice V2 - Master"
true: 
  push: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with: 
          python-version: "${{ matrix.python-version }}"
      - 
        name: "Set up Python ${{ matrix.python-version }}"
        run: |
            pipenv install
            pipenv run test
        uses: dschep/install-pipenv-action@v1
        with: 
          python-version: "${{ matrix.python-version }}"
      - 
        env: 
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE_BRANCHES: master
          WITH_V: true
        id: version-bump
        name: "Bump version and push tag"
        uses: anothrNick/github-tag-action@1.26.0
        
    strategy: 
      matrix: 
        python-version: 
          - "3.9.1"
